@base_url = https://localhost:7061/portalcolaborador

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
  "nome": "Joao da Silva",
  "cpf": "12345678910",
  "status": 1,
  "cargo": 1
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar
### Listar Funcionario por CPF
GET {{base_url}}/funcionario/listar
{
  "cpf": "123.456.789-10"
}

### Listar um funcionario
GET {{base_url}}/funcionario/listar/7

### Editar um Funcionario
PUT {{base_url}}/funcionario/atualizar/1

{
  "cargo": 1
}

### Deletar Funcionario
DELETE {{base_url}}/funcionario/deletar/2