@base_url = https://localhost:7061/portalcolaborador

### Criação de um novo funcionário
POST {{base_url}}/jornada/cadastrar
Content-Type: application/json

{
  "funcionarioId": 6
}

### Obtenção de todos os funcionários
GET {{base_url}}/jornada/listar