@base_url = https://localhost:7061/portalcolaborador

### cadastrar Usuario
POST {{base_url}}/login/cadastrar
Content-Type: application/json

{
  "user": "joao",
  "senha": "teste",
  "Funcionario": {
    "Cpf": "45612378910"
  }
}

### Obtenção de todos os Usuarios
GET {{base_url}}/login/listar

### Deletar um Usuario
DELETE {{base_url}}/login/deletar/

### Editar usuario
PUT {{base_url}}/login/atualizar/8  

{
    "user": "andersongross",
    "senha": "123"
}